language: ruby

# So as to use container-based infrastructure 
sudo: false

# The first three options (rvm, env, and gemfile)
# create the build matrix.
matrix:
  include:
    - rvm: 2.5.1
      gemfile: Gemfile
      env: PREP_TARGET=prep_ccs DEPLOY_TARGET=deploy_ccs PUSH_TARGET=push_ccs 
    - rvm: 2.5.1
      gemfile: Gemfile
      env: PREP_TARGET=prep_gh  DEPLOY_TARGET=deploy_gh  PUSH_TARGET=push_gh 


# Use cache, if possible (https://docs.travis-ci.com/user/caching/)
cache: bundler

bundler_args: --retry 3


# Upgrade system library
# This is to circumvent bug: https://github.com/travis-ci/travis-ci/issues/8978
# before_install:
#   - gem update --system
#   - gem install bundler

# Install Jekyll and dependencies.
install:
  - bundle config build.nokogiri --use-system-libraries
  - bundle install

# branch whitelist
# The source branch and every branch starts with "pages-" for proposed changes
branches:
  only:
    - source
    - /pages-(.*)/

# Run rakefile deploy task and a script so that travis-ci won't timeout
script: 
  - bundle exec rake site:$PREP_TARGET --quiet
  - bundle exec ./summat.sh; bundle exec rake site:$DEPLOY_TARGET --quiet
  - bundle exec rake site:$PUSH_TARGET --quiet


# Using personal access token to let Travis push to GitHub, following:
# https://github.com/steveklabnik/automatically_update_github_pages_with_travis_example
# and entering the variables GIT_NAME, GIT_MAIL, and GH_TOKEN into the Travis settings for the repository'
# https://travis-ci.org/TheoreticalAstrophysicsGroup/TheoreticalAstrophysicsGroup.github.io/settings
#
#
# Previously we used the following:
#
# Generate your secure token with the travis gem:
# 1) get Github token from your Travis CI profile page
# 2) gem install travis
# 3) travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_MAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
# 4) add under:
 
# Global environmental variables
#env:
#  global:
#    secure: {token}


