# Travis CI-github-CCS build and deployment
relative_source:  TheoreticalAstrophysicsGroup.github.io
destination_loc: ../loc_version
destination_gh: ../gh_version
destination_ccs: ../ccs_version
orgname: TheoreticalAstrophysicsGroup
branch: source
post_limit: 10

