name: send-kenkyuin-kaigi-email

on:
  schedule:
    - cron: '0 9 22-28 1,3,4-7,9-12 TUE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  send_kenkyuin_kaigi_email:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m')" >> $GITHUB_ENV
          echo "month=$(date +'%m')" >> $GITHUB_ENV
          echo "day=$(date +'%d')" >> $GITHUB_ENV
          echo "day_kaigi=$(($(date +'%d') + 7))" >> $GITHUB_ENV

      - name: Send mail
        if: github.event.schedule != '0 9 22-28 1,3,4-7,9-12 MON,WED,THU,FRI,SAT,SUN'
        uses: dawidd6/action-send-mail@v3
        with:

          # Specify connection via URL
          # Format: smtp+starttls://user:password@server:port
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          
          # Server port, default 25:
          server_port: 465

          # Required mail subject:
          subject: 【依頼】${{ env.month }}/${{ env.day_kaigi }} 研究員会議報告

          # Required recipients' addresses:
          to: ayw@ccs.tsukuba.ac.jp

          # Required sender full name (address can be skipped):
          from: Alexander Y. Wagner <ayw@ccs.tsukuba.ac.jp>

          # html body:
          html_body: |
            宇宙物理理論研究室の教員および研究員のみなさま
            （それ以外の方は無視してください）

            来週の火曜に研究員会議が開催されます。
            報告事項のある方は Overleaf で前日の深夜までにお願いします。

            ```
            ${{ secrets.KENKYUIN_KAIGI_OVERLEAF_LINK }}
            ```

            編集するのは `${{ env.date }}/` のディレクトリです。

            よろしくお願いします。

            Alex


            BibTeX ファイルの内容
            * 受賞： `awards.bib`
            * 著書（全体・章・解説記事）： `books.bib`
            * 国内研究会（招待講演）： `conf_dom_invited.bib`
            * 国内研究会（一般講演）： `conf_dom_contrib.bib`
            * 国際研究会（招待講演）： `conf_intl_invited.bib`
            * 国際研究会（一般講演）： `conf_intl_contrib.bib`
            * 集中講義： `lectures.bib`
            * 異分野連携・国際連携・国際活動など（月別）： `linkages.bib`
            * ミーティング： `meetings.bib`
            * その他： `miscellaneous.bib`
            * 論文（審査付き）： `papers_refereed.bib`
            * 論文（審査無し）： `papers_non-refereed.bib`
            * シンポジウム・研究会・スクール等の開催実績： `soc_loc.bib`
            * 社会貢献・国際貢献： `social_benefits.bib`

            注意点：
            * 記入例はそれぞれのファイルのヘダーにあります。
            * 論文は NASA ADS からの BibTeX export をそのまま貼り付けるだけで結構です。
            * 論文は掲載されたもののみでお願いします。Preprint 段階のものはのせないでください。
            * 共著者又は共発表者は and でつなげてリストアップしてください。E.g., `author = {福島肇 and 矢島秀伸 and 安部牧人},`
            * ポスター発表の場合は `presentation = {poster},` 基調講演の場合は `presentation = {keynote},` にしてください。
            * コンパイルされるメインファイルは `${{ env.date }}-Astro_Report.tex` ですが，そのファイルは編集しないでください。

          # Optional HTML body read from file:
          #html_body: file://README.html

          # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com

          # Optional blind carbon copy recipients:
          #bcc: r2d2@example.com,hansolo@example.com

          # Optional recipient of the email response:
          #reply_to: luke@example.com

          # Optional Message ID this message is replying to:
          #in_reply_to: <random-luke@example.com>

          # Optional unsigned/invalid certificates allowance:
          ignore_cert: false

          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true

          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js

          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: normal
          
